/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import com.FireWatch.classes.Usuario;
import com.FireWatch.classes.UsuarioLogado;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author User
 */
public class EditarPerfil extends javax.swing.JFrame {

    /**
     * Creates new form EditarPerfil
     */
    public EditarPerfil() {
        initComponents();
        try {
        // Cria a máscara para o formato (xx)xxxx-xxxx
        MaskFormatter mascara = new MaskFormatter("(##)#####-####");
        mascara.setPlaceholderCharacter('_');  // Preenche com _ os campos vazios

        // Aplica a máscara ao JFormattedTextField
        Telefonepf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascara));
        
        }catch (Exception e) {
        e.printStackTrace();
        }
        
        String nomeUsuario = UsuarioLogado.getInstance().getNomeUsuario();       
        Usuario usuario = new Usuario();
        usuario.setUsuario(nomeUsuario);
                
        try { 
            Usuario usu = usuario.BuscarUsu();
            
            if (usu !=null) {  
            nomePerfil.setText(nomeUsuario);
            
            Nomepf.setText(usu.getNome());
            
            Telefonepf.setText(usu.getTelefone());
            
            Estadopf.setText(usu.getEstado());
            
            Cidadepf.setText(usu.getCidade());
            
            Senhapf.setText(usu.getSenha());
            
            
            }
        } catch (SQLException ex) {
                Logger.getLogger(Perfil.class.getName()).log(Level.SEVERE, null, ex);
            }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nomepf = new javax.swing.JTextField();
        nomePerfil = new javax.swing.JTextField();
        Estadopf = new javax.swing.JTextField();
        Cidadepf = new javax.swing.JTextField();
        btAtualizarUsu = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Senhapf = new javax.swing.JPasswordField();
        Telefonepf = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        mostraSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(685, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        Nomepf.setBackground(new java.awt.Color(123, 0, 0));
        Nomepf.setForeground(new java.awt.Color(221, 221, 221));
        Nomepf.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        Nomepf.setBorder(null);
        Nomepf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomepfActionPerformed(evt);
            }
        });
        getContentPane().add(Nomepf);
        Nomepf.setBounds(170, 212, 340, 30);

        nomePerfil.setBackground(new java.awt.Color(123, 0, 0));
        nomePerfil.setForeground(new java.awt.Color(221, 221, 221));
        nomePerfil.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        nomePerfil.setBorder(null);
        nomePerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePerfilActionPerformed(evt);
            }
        });
        getContentPane().add(nomePerfil);
        nomePerfil.setBounds(170, 290, 340, 30);

        Estadopf.setBackground(new java.awt.Color(123, 0, 0));
        Estadopf.setForeground(new java.awt.Color(221, 221, 221));
        Estadopf.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        Estadopf.setBorder(null);
        Estadopf.setHorizontalAlignment(Estadopf.CENTER);
        getContentPane().add(Estadopf);
        Estadopf.setBounds(164, 440, 90, 30);

        Cidadepf.setBackground(new java.awt.Color(123, 0, 0));
        Cidadepf.setForeground(new java.awt.Color(221, 221, 221));
        Cidadepf.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        Cidadepf.setBorder(null);
        getContentPane().add(Cidadepf);
        Cidadepf.setBounds(325, 438, 190, 30);

        btAtualizarUsu.setOpaque(false); // botão transparente
        btAtualizarUsu.setContentAreaFilled(false); // Remove a cor de fundo
        btAtualizarUsu.setBorderPainted(false); // Remove a borda
        btAtualizarUsu.setForeground(new java.awt.Color(221, 221, 221));
        btAtualizarUsu.setBackground(new java.awt.Color(40, 40, 40));
        btAtualizarUsu.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btAtualizarUsu.setText("EDITAR DADOS");
        btAtualizarUsu.setForeground(new java.awt.Color(221, 221, 221));

        btAtualizarUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            private javax.swing.Timer timer;

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (timer !=null) {
                    timer.stop();
                }

                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.max(255, btAtualizarUsu.getForeground().getRed() - 10);
                    int g = Math.max(145, btAtualizarUsu.getForeground().getGreen() - 10);
                    int b = Math.max(77, btAtualizarUsu.getForeground().getBlue() - 10);
                    btAtualizarUsu.setForeground(new java.awt.Color(r, g, b));
                    if (r <= 255 && g <= 145 && b <= 77) {
                        timer.stop();
                    }
                });
                timer.start();
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (timer != null) {
                    timer.stop();
                }
                // Timer para a animação de volta à cor original
                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.min(255, btAtualizarUsu.getForeground().getRed() + 10);
                    int g = Math.min(255, btAtualizarUsu.getForeground().getGreen() + 10);
                    int b = Math.min(255, btAtualizarUsu.getForeground().getBlue() + 10);
                    btAtualizarUsu.setForeground(new java.awt.Color(r, g, b));
                    if (r >= 221 && g >= 221 && b >= 221) {
                        timer.stop();
                    }
                });
                timer.start();
            }
        });
        btAtualizarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarUsuActionPerformed(evt);
            }
        });
        getContentPane().add(btAtualizarUsu);
        btAtualizarUsu.setBounds(198, 560, 280, 50);

        jButton2.setBackground(new java.awt.Color(123, 0, 0));
        jButton2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(221, 221, 221));
        jButton2.setText("VOLTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 620, 80, 26);

        Senhapf.setBackground(new java.awt.Color(123, 0, 0));
        Senhapf.setForeground(new java.awt.Color(221, 221, 221));
        Senhapf.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        Senhapf.setBorder(null);
        getContentPane().add(Senhapf);
        Senhapf.setBounds(170, 510, 310, 30);

        Telefonepf.setBackground(new java.awt.Color(123, 0, 0));
        Telefonepf.setForeground(new java.awt.Color(221, 221, 221));
        Telefonepf.setBorder(null);
        Telefonepf.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        Telefonepf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonepfActionPerformed(evt);
            }
        });
        getContentPane().add(Telefonepf);
        Telefonepf.setBounds(170, 366, 340, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Documentos\\NetBeansProjects\\A3_Testes\\src\\main\\resources\\images\\TelaCriarConta.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 670);

        mostraSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostraSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(mostraSenha);
        mostraSenha.setBounds(488, 507, 34, 36);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomePerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePerfilActionPerformed

    private void btAtualizarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarUsuActionPerformed
        String nomeC = Nomepf.getText();
        String perfilC = nomePerfil.getText();
        String foneC = Telefonepf.getText();
        String estadoC = Estadopf.getText();
        String cidadeC = Estadopf.getText();
        String senhaC = new String(Senhapf.getPassword());
        
        if ("".equals(nomeC) | "".equals(perfilC) | "".equals(foneC) | "".equals(estadoC) | "".equals(cidadeC) | "".equals(senhaC)) {
                JOptionPane.showMessageDialog(null, "Campos obrigatórios não preenchidos!");
        } else {       
            int x = JOptionPane.showConfirmDialog(null, "Tem certeza que quer alterar seus dados?", "Dados", JOptionPane.YES_NO_OPTION);

            if(x == 0) {
                try {
                    // TODO add your handling code here:
                    String usuLogado = UsuarioLogado.getInstance().getNomeUsuario();

                    Usuario usuat = new Usuario();
                    usuat.setUsuario(usuLogado);
                    usuat = usuat.BuscarUsu();

                    String nome = Nomepf.getText();
                    String usuario = nomePerfil.getText();
                    String fone = Telefonepf.getText();
                    String estado = Estadopf.getText();
                    String cidade = Cidadepf.getText();
                    String senha = new String (Senhapf.getPassword());
                    int codigo = usuat.getCodigo();
                    
                    //verifica se o nome de usuario já está sendo utilizado
                if (usuat.UsuExistente(usuario) && !usuario.equals(usuat.getUsuario())) {
                    JOptionPane.showMessageDialog(null, "O nome de usuário já está sendo utilizado!");
                    return; 
                }
                                     
                    usuat.setNome(nome);
                    usuat.setUsuario(usuario);
                    usuat.setTelefone(fone);
                    usuat.setEstado(estado);
                    usuat.setCidade(cidade);
                    usuat.setSenha(senha);
                    usuat.setCodigo(codigo);
                    Login login = new Login();
                    login.setVisible(true);
                    this.dispose();

                    usuat.EditarUsu();
                } catch (SQLException ex) {
                    Logger.getLogger(EditarPerfil.class.getName()).log(Level.SEVERE, null, ex);                
                }
            } else {

            }
        }
    }//GEN-LAST:event_btAtualizarUsuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int x = this.getLocation().x;
        int y = this.getLocation().y;
        
        Perfil perfil = new Perfil();
        perfil.setLocation(x, y);
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NomepfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomepfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomepfActionPerformed

    private void mostraSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostraSenhaActionPerformed
        // TODO add your handling code here:
        if (Senhapf.getEchoChar() != '\u0000') {
            Senhapf.setEchoChar('\u0000');
        }else {
            Senhapf.setEchoChar('*');
        }
        if (Nomepf.getText()==null) 
        System.out.println(Nomepf.getText());
    }//GEN-LAST:event_mostraSenhaActionPerformed

    private void TelefonepfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonepfActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TelefonepfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cidadepf;
    private javax.swing.JTextField Estadopf;
    private javax.swing.JTextField Nomepf;
    private javax.swing.JPasswordField Senhapf;
    private javax.swing.JFormattedTextField Telefonepf;
    private javax.swing.JButton btAtualizarUsu;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mostraSenha;
    private javax.swing.JTextField nomePerfil;
    // End of variables declaration//GEN-END:variables
}
