/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.*;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        Home = new javax.swing.JButton();
        Denuncia = new javax.swing.JButton();
        Queimadas = new javax.swing.JButton();
        Perfil = new javax.swing.JButton();
        AboutUs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(970, 625));
        setResizable(false);
        getContentPane().setLayout(null);

        Home.setOpaque(false); // botão transparente
        Home.setContentAreaFilled(false); // Remove a cor de fundo
        Home.setBorderPainted(false); // Remove a borda
        Home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Home.setText("HOME");
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        Home.setForeground(new java.awt.Color(221, 221, 221));

        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            private javax.swing.Timer timer; //animação

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (timer !=null) {
                    timer.stop();
                }
                //mudança de cor
                timer = new javax.swing.Timer(18, e -> { //velocidade
                    int r = Math.max(0, Home.getForeground().getRed() - 10);
                    int g = Math.max(0, Home.getForeground().getGreen() - 10);
                    int b = Math.max(0, Home.getForeground().getBlue() - 10);
                    Home.setForeground(new java.awt.Color(r, g, b));
                    if (r <= 0 && g <= 0 && b <= 0) {
                        timer.stop(); // Para o timer quando a cor preta for atingida
                    }
                });
                timer.start(); // Começa a animação
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (timer != null) {
                    timer.stop();
                }
                // Timer para a animação de volta à cor original
                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.min(255, Home.getForeground().getRed() + 10);
                    int g = Math.min(255, Home.getForeground().getGreen() + 10);
                    int b = Math.min(255, Home.getForeground().getBlue() + 10);
                    Home.setForeground(new java.awt.Color(r, g, b));
                    if (r >= 221 && g >= 221 && b >= 221) {
                        timer.stop();
                    }
                });
                timer.start();
            }
        });
        getContentPane().add(Home);
        Home.setBounds(10, 10, 120, 44);

        Denuncia.setOpaque(false);
        Denuncia.setContentAreaFilled(false);
        Denuncia.setBorderPainted(false);
        Denuncia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Denuncia.setText("DENUNCIE");
        Denuncia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Denuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DenunciaActionPerformed(evt);
            }
        });
        Denuncia.setForeground(new java.awt.Color(221, 221, 221));

        Denuncia.addMouseListener(new java.awt.event.MouseAdapter() {
            private javax.swing.Timer timer;

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (timer !=null) {
                    timer.stop();
                }

                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.max(123, Denuncia.getForeground().getRed() - 10);
                    int g = Math.max(0, Denuncia.getForeground().getGreen() - 10);
                    int b = Math.max(0, Denuncia.getForeground().getBlue() - 10);
                    Denuncia.setForeground(new java.awt.Color(r, g, b));
                    if (r <= 123 && g <= 0 && b <= 0) {
                        timer.stop();
                    }
                });
                timer.start();
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (timer != null) {
                    timer.stop();
                }
                // Timer para a animação de volta à cor original
                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.min(255, Denuncia.getForeground().getRed() + 10);
                    int g = Math.min(255, Denuncia.getForeground().getGreen() + 10);
                    int b = Math.min(255, Denuncia.getForeground().getBlue() + 10);
                    Denuncia.setForeground(new java.awt.Color(r, g, b));
                    if (r >= 221 && g >= 221 && b >= 221) {
                        timer.stop();
                    }
                });
                timer.start();
            }
        });
        getContentPane().add(Denuncia);
        Denuncia.setBounds(154, 10, 120, 44);

        Queimadas.setOpaque(false);
        Queimadas.setContentAreaFilled(false);
        Queimadas.setBorderPainted(false);
        Queimadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Queimadas.setText("QUEIMADAS");
        Queimadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Queimadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueimadasActionPerformed(evt);
            }
        });
        Queimadas.setForeground(new java.awt.Color(221, 221, 221));

        Queimadas.addMouseListener(new java.awt.event.MouseAdapter() {
            private javax.swing.Timer timer;

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (timer !=null) {
                    timer.stop();
                }

                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.max(123, Queimadas.getForeground().getRed() - 10);
                    int g = Math.max(0, Queimadas.getForeground().getGreen() - 10);
                    int b = Math.max(0, Queimadas.getForeground().getBlue() - 10);
                    Queimadas.setForeground(new java.awt.Color(r, g, b));
                    if (r <= 123 && g <= 0 && b <= 0) {
                        timer.stop();
                    }
                });
                timer.start();
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (timer != null) {
                    timer.stop();
                }
                // Timer para a animação de volta à cor original
                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.min(255, Queimadas.getForeground().getRed() + 10);
                    int g = Math.min(255, Queimadas.getForeground().getGreen() + 10);
                    int b = Math.min(255, Queimadas.getForeground().getBlue() + 10);
                    Queimadas.setForeground(new java.awt.Color(r, g, b));
                    if (r >= 221 && g >= 221 && b >= 221) {
                        timer.stop();
                    }
                });
                timer.start();
            }
        });
        getContentPane().add(Queimadas);
        Queimadas.setBounds(297, 10, 120, 44);

        Perfil.setOpaque(false);
        Perfil.setContentAreaFilled(false);
        Perfil.setBorderPainted(false);
        Perfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Perfil.setText("PERFIL");
        Perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilActionPerformed(evt);
            }
        });
        Perfil.setForeground(new java.awt.Color(221, 221, 221));

        Perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            private javax.swing.Timer timer;

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (timer !=null) {
                    timer.stop();
                }

                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.max(123, Perfil.getForeground().getRed() - 10);
                    int g = Math.max(0, Perfil.getForeground().getGreen() - 10);
                    int b = Math.max(0, Perfil.getForeground().getBlue() - 10);
                    Perfil.setForeground(new java.awt.Color(r, g, b));
                    if (r <= 123 && g <= 0 && b <= 0) {
                        timer.stop();
                    }
                });
                timer.start();
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (timer != null) {
                    timer.stop();
                }
                // Timer para a animação de volta à cor original
                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.min(255, Perfil.getForeground().getRed() + 10);
                    int g = Math.min(255, Perfil.getForeground().getGreen() + 10);
                    int b = Math.min(255, Perfil.getForeground().getBlue() + 10);
                    Perfil.setForeground(new java.awt.Color(r, g, b));
                    if (r >= 221 && g >= 221 && b >= 221) {
                        timer.stop();
                    }
                });
                timer.start();
            }
        });
        getContentPane().add(Perfil);
        Perfil.setBounds(587, 10, 120, 44);

        AboutUs.setOpaque(false);
        AboutUs.setContentAreaFilled(false);
        AboutUs.setBorderPainted(false);
        AboutUs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AboutUs.setText("SOBRE NÓS");
        AboutUs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });
        AboutUs.setForeground(new java.awt.Color(221, 221, 221));

        AboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            private javax.swing.Timer timer;

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (timer !=null) {
                    timer.stop();
                }

                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.max(123, AboutUs.getForeground().getRed() - 10);
                    int g = Math.max(0, AboutUs.getForeground().getGreen() - 10);
                    int b = Math.max(0, AboutUs.getForeground().getBlue() - 10);
                    AboutUs.setForeground(new java.awt.Color(r, g, b));
                    if (r <= 123 && g <= 0 && b <= 0) {
                        timer.stop();
                    }
                });
                timer.start();
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (timer != null) {
                    timer.stop();
                }
                // Timer para a animação de volta à cor original
                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.min(255, AboutUs.getForeground().getRed() + 10);
                    int g = Math.min(255, AboutUs.getForeground().getGreen() + 10);
                    int b = Math.min(255, AboutUs.getForeground().getBlue() + 10);
                    AboutUs.setForeground(new java.awt.Color(r, g, b));
                    if (r >= 221 && g >= 221 && b >= 221) {
                        timer.stop();
                    }
                });
                timer.start();
            }
        });
        getContentPane().add(AboutUs);
        AboutUs.setBounds(442, 10, 120, 44);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Documentos\\NetBeansProjects\\A3_Testes\\src\\main\\resources\\images\\TelaHome.png")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(970, 610));
        jLabel2.setMinimumSize(new java.awt.Dimension(970, 610));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 960, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HomeActionPerformed

    private void DenunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DenunciaActionPerformed
        // TODO add your handling code here:
        //pega a posição atual da tela
        int x = this.getLocationOnScreen().x;
        int y = this.getLocationOnScreen().y;
        
        Denuncia denuncia = new Denuncia();
        denuncia.setLocation(x, y);
        denuncia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DenunciaActionPerformed

    private void QueimadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueimadasActionPerformed
        // TODO add your handling code here:
        int x = this.getLocation().x;
        int y = this.getLocation().y;
        
        Queimadas queimadas = new Queimadas();
        queimadas.setLocation(x, y);
        queimadas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_QueimadasActionPerformed

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed
        // TODO add your handling code here:
        int x = this.getLocation().x;
        int y = this.getLocation().y;
        
        SobreNos sobreNos = new SobreNos();
        sobreNos.setLocation(x,y);
        sobreNos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AboutUsActionPerformed

    private void PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilActionPerformed
        // TODO add your handling code here:
        int x = this.getLocation().x;
        int y = this.getLocation().y;
        
        Perfil perfil = new Perfil();
        perfil.setLocation(x,y);
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUs;
    private javax.swing.JButton Denuncia;
    private javax.swing.JButton Home;
    private javax.swing.JButton Perfil;
    private javax.swing.JButton Queimadas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}
