/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import com.FireWatch.DAO.ConnectionFactory;
import com.FireWatch.classes.Usuario;
import com.FireWatch.classes.UsuarioLogado;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.FontMetrics;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //centralizar telas
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLogin = new javax.swing.JButton();
        LoginInput = new javax.swing.JTextField();
        senhaLogin = new javax.swing.JPasswordField();
        semConta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(649, 657));
        setResizable(false);
        getContentPane().setLayout(null);

        btLogin.setForeground(new java.awt.Color(221, 221, 221));

        btLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            private javax.swing.Timer timer; //animação

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (timer !=null) {
                    timer.stop();
                }
                //mudança de cor
                timer = new javax.swing.Timer(18, e -> { //velocidade
                    int r = Math.max(123, btLogin.getForeground().getRed() - 10);
                    int g = Math.max(230, btLogin.getForeground().getGreen() - 10);
                    int b = Math.max(76, btLogin.getForeground().getBlue() - 10);
                    btLogin.setForeground(new java.awt.Color(r, g, b));
                    if (r <= 123 && g <= 230 && b <= 76) {
                        timer.stop(); // Para o timer quando a cor preta for atingida
                    }
                });
                timer.start(); // Começa a animação
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (timer != null) {
                    timer.stop();
                }
                // Timer para a animação de volta à cor original
                timer = new javax.swing.Timer(21, e -> {
                    int r = Math.min(255, btLogin.getForeground().getRed() + 10);
                    int g = Math.min(255, btLogin.getForeground().getGreen() + 10);
                    int b = Math.min(255, btLogin.getForeground().getBlue() + 10);
                    btLogin.setForeground(new java.awt.Color(r, g, b));
                    if (r >= 221 && g >= 221 && b >= 221) {
                        timer.stop();
                    }
                });
                timer.start();
            }
        });
        btLogin.setBackground(new java.awt.Color(123, 0, 0));
        btLogin.setOpaque(false);
        btLogin.setContentAreaFilled(false);
        btLogin.setBorderPainted(false);
        btLogin.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        btLogin.setText("Login");
        btLogin.setForeground(new java.awt.Color(221, 221, 221));
        btLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        btLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btLogin);
        btLogin.setBounds(228, 500, 220, 40);

        LoginInput.setBackground(new java.awt.Color(123, 0, 0));
        LoginInput.setForeground(new java.awt.Color(221, 221, 221));
        LoginInput.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        LoginInput.setBorder(null);
        LoginInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginInputActionPerformed(evt);
            }
        });
        getContentPane().add(LoginInput);
        LoginInput.setBounds(190, 310, 320, 40);

        senhaLogin.setBackground(new java.awt.Color(123, 0, 0));
        senhaLogin.setForeground(new java.awt.Color(221, 221, 211));
        senhaLogin.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        senhaLogin.setBorder(null);
        senhaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaLoginActionPerformed(evt);
            }
        });
        getContentPane().add(senhaLogin);
        senhaLogin.setBounds(190, 418, 300, 30);

        semConta.setOpaque(false);
        semConta.setContentAreaFilled(false);
        semConta.setBorderPainted(false);
        semConta.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        semConta.setText("Não tenho conta");
        semConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        semConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semContaActionPerformed(evt);
            }
        });
        semConta.setForeground(new java.awt.Color(0, 0, 0));

        semConta.addMouseListener(new java.awt.event.MouseAdapter() {
            private javax.swing.Timer timer; //animação

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (timer !=null) {
                    timer.stop();
                }
                //mudança de cor
                timer = new javax.swing.Timer(18, e -> { //velocidade
                    int r = Math.max(0, semConta.getForeground().getRed() - 10);
                    int g = Math.max(72, semConta.getForeground().getGreen() - 10);
                    int b = Math.max(255, semConta.getForeground().getBlue() - 10);
                    semConta.setForeground(new java.awt.Color(r, g, b));
                    if (r <= 0 && g <= 255 && b <= 255) {
                        timer.stop(); //para quando encontra a cor
                    }
                });
                timer.start(); // Começa a animação
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (timer != null) {
                    timer.stop();
                }
                // Timer para a animação de volta à cor original
                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.min(0, semConta.getForeground().getRed() + 10);
                    int g = Math.min(0, semConta.getForeground().getGreen() + 10);
                    int b = Math.min(0, semConta.getForeground().getBlue() + 10);
                    semConta.setForeground(new java.awt.Color(r, g, b));
                    if (r >= 0 && g >= 0 && b >= 0) {
                        timer.stop();
                    }
                });
                timer.start();
            }
        });
        getContentPane().add(semConta);
        semConta.setBounds(225, 550, 230, 44);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Documentos\\NetBeansProjects\\A3_Testes\\src\\main\\resources\\images\\TelaLogin.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 660);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(492, 412, 40, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginInputActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
        String usu = LoginInput.getText();
        String senha = new String(senhaLogin.getPassword());
        
        if ("FireWatch".equals(usu) && "adm123".equals(senha)) {

            
            TelaAdm ta = new TelaAdm();
            ta.setVisible(true);

            this.dispose();
            
        } else {        
            Usuario usuario = new Usuario();
            usuario.setUsuario(usu);
            usuario.setSenha(senha);

            try {
                if (usuario.ValidaUsu()) {
                    UsuarioLogado.getInstance().setNomeUsuario(usu);
                    UsuarioLogado.getInstance().setSenhaUsuario(senha);
                    System.out.println();
                    Home home = new Home();
                    home.setVisible(true);
                    this.dispose();
                }else {
                    JOptionPane.showMessageDialog(null, "Usuário e/ou senha incorretos!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }     

            ConnectionFactory cf = new ConnectionFactory();
            cf.obtemConexao();        
        }
    }//GEN-LAST:event_btLoginActionPerformed

    private void senhaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaLoginActionPerformed

    private void semContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semContaActionPerformed
        // TODO add your handling code here:
        CriarConta cC = new CriarConta();
        cC.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_semContaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (senhaLogin.getEchoChar() != '\u0000') {
            senhaLogin.setEchoChar('\u0000');
        }else {
            senhaLogin.setEchoChar('*');
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LoginInput;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton semConta;
    private javax.swing.JPasswordField senhaLogin;
    // End of variables declaration//GEN-END:variables
}
