/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import com.FireWatch.DAO.ConnectionFactory;
import java.awt.Desktop;
import java.net.URI;
import java.net.URLEncoder;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Queimadas extends javax.swing.JFrame {

    /**
     * Creates new form Queimadas
     */
    public Queimadas() {
        initComponents();   
        
                
        String cidade = txtcidade.getText();
        String sql = "";
        
        DefaultTableModel model = new DefaultTableModel
            (new String[]{"Estado", "Cidade", "Endereço", "Número ou KM", "Data", "Hora", "Gravidade"},0) {
                public boolean isCellEditable(int row, int column) {
                    return false;
                    }
        };
        
            sql = "SELECT * FROM tb_denuncias ORDER BY numden DESC";
        
        ConnectionFactory cf = new ConnectionFactory();
        
        try(Connection conn = cf.obtemConexao();
                PreparedStatement ps = conn.prepareStatement(sql);) {
            if (!"".equals(cidade)) {
                ps.setString(1, cidade);
            }
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
                String txtestado = rs.getString("estadoden");
                String txtcidade = rs.getString("cidadeden");
                String txtrua = rs.getString("endeden");
                String txtnum = rs.getString("numeden");
                String txtdata = rs.getString("dataden");
                String txthora = rs.getString("horaden");
                String txtgrav = rs.getString("gravden");
                
                model.addRow(new Object[]{txtestado, txtcidade, txtrua, txtnum, txtdata, txthora, txtgrav});
                        
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Não localizado!");
        }    
        
        tabela.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Perfil = new javax.swing.JButton();
        txtcidade = new javax.swing.JTextField();
        listar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        buscar = new javax.swing.JButton();
        AboutUs = new javax.swing.JButton();
        Denuncia = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        Queimadas = new javax.swing.JButton();
        Perfil1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        Perfil.setOpaque(false);
        Perfil.setContentAreaFilled(false);
        Perfil.setBorderPainted(false);
        Perfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Perfil.setText("PERFIL");
        Perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilActionPerformed(evt);
            }
        });
        Perfil.setForeground(new java.awt.Color(221, 221, 221));

        Perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            private javax.swing.Timer timer;

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (timer !=null) {
                    timer.stop();
                }

                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.max(123, Perfil.getForeground().getRed() - 10);
                    int g = Math.max(0, Perfil.getForeground().getGreen() - 10);
                    int b = Math.max(0, Perfil.getForeground().getBlue() - 10);
                    Perfil.setForeground(new java.awt.Color(r, g, b));
                    if (r <= 123 && g <= 0 && b <= 0) {
                        timer.stop();
                    }
                });
                timer.start();
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (timer != null) {
                    timer.stop();
                }
                // Timer para a animação de volta à cor original
                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.min(255, Perfil.getForeground().getRed() + 10);
                    int g = Math.min(255, Perfil.getForeground().getGreen() + 10);
                    int b = Math.min(255, Perfil.getForeground().getBlue() + 10);
                    Perfil.setForeground(new java.awt.Color(r, g, b));
                    if (r >= 221 && g >= 221 && b >= 221) {
                        timer.stop();
                    }
                });
                timer.start();
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(972, 637));
        setResizable(false);
        getContentPane().setLayout(null);

        txtcidade.setBackground(new java.awt.Color(244, 244, 244));
        txtcidade.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txtcidade.setBorder(null);
        getContentPane().add(txtcidade);
        txtcidade.setBounds(70, 118, 600, 30);

        listar.setOpaque(false);
        listar.setContentAreaFilled(false);
        listar.setBorderPainted(false);
        listar.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        listar.setForeground(new java.awt.Color(221, 221, 221));
        listar.setText("Listar");
        listar.setBorder(null);
        listar.setForeground(new java.awt.Color(221, 221, 221));

        listar.addMouseListener(new java.awt.event.MouseAdapter() {
            private javax.swing.Timer timer;

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (timer !=null) {
                    timer.stop();
                }

                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.max(123, listar.getForeground().getRed() - 10);
                    int g = Math.max(0, listar.getForeground().getGreen() - 10);
                    int b = Math.max(0, listar.getForeground().getBlue() - 10);
                    listar.setForeground(new java.awt.Color(r, g, b));
                    if (r <= 123 && g <= 0 && b <= 0) {
                        timer.stop();
                    }
                });
                timer.start();
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (timer != null) {
                    timer.stop();
                }
                // Timer para a animação de volta à cor original
                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.min(255, listar.getForeground().getRed() + 10);
                    int g = Math.min(255, listar.getForeground().getGreen() + 10);
                    int b = Math.min(255, listar.getForeground().getBlue() + 10);
                    listar.setForeground(new java.awt.Color(r, g, b));
                    if (r >= 221 && g >= 221 && b >= 221) {
                        timer.stop();
                    }
                });
                timer.start();
            }
        });
        listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarActionPerformed(evt);
            }
        });
        getContentPane().add(listar);
        listar.setBounds(720, 107, 170, 50);

        tabela.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Estado", "Cidade", "Rua", "Número ou KM", "Data", "Hora", "Gravidade"
            }
        ) {

            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 180, 920, 350);

        buscar.setOpaque(false);
        buscar.setContentAreaFilled(false);
        buscar.setBorderPainted(false);
        buscar.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        buscar.setText("Buscar endereço");
        buscar.setForeground(new java.awt.Color(221, 221, 221));

        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            private javax.swing.Timer timer;

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (timer !=null) {
                    timer.stop();
                }

                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.max(123, buscar.getForeground().getRed() - 10);
                    int g = Math.max(0, buscar.getForeground().getGreen() - 10);
                    int b = Math.max(0, buscar.getForeground().getBlue() - 10);
                    buscar.setForeground(new java.awt.Color(r, g, b));
                    if (r <= 123 && g <= 0 && b <= 0) {
                        timer.stop();
                    }
                });
                timer.start();
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (timer != null) {
                    timer.stop();
                }
                // Timer para a animação de volta à cor original
                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.min(255, buscar.getForeground().getRed() + 10);
                    int g = Math.min(255, buscar.getForeground().getGreen() + 10);
                    int b = Math.min(255, buscar.getForeground().getBlue() + 10);
                    buscar.setForeground(new java.awt.Color(r, g, b));
                    if (r >= 221 && g >= 221 && b >= 221) {
                        timer.stop();
                    }
                });
                timer.start();
            }
        });
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar);
        buscar.setBounds(370, 538, 220, 50);

        AboutUs.setOpaque(false);
        AboutUs.setContentAreaFilled(false);
        AboutUs.setBorderPainted(false);
        AboutUs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AboutUs.setText("SOBRE NÓS");
        AboutUs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });
        AboutUs.setForeground(new java.awt.Color(221, 221, 221));

        AboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            private javax.swing.Timer timer;

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (timer !=null) {
                    timer.stop();
                }

                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.max(123, AboutUs.getForeground().getRed() - 10);
                    int g = Math.max(0, AboutUs.getForeground().getGreen() - 10);
                    int b = Math.max(0, AboutUs.getForeground().getBlue() - 10);
                    AboutUs.setForeground(new java.awt.Color(r, g, b));
                    if (r <= 123 && g <= 0 && b <= 0) {
                        timer.stop();
                    }
                });
                timer.start();
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (timer != null) {
                    timer.stop();
                }
                // Timer para a animação de volta à cor original
                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.min(255, AboutUs.getForeground().getRed() + 10);
                    int g = Math.min(255, AboutUs.getForeground().getGreen() + 10);
                    int b = Math.min(255, AboutUs.getForeground().getBlue() + 10);
                    AboutUs.setForeground(new java.awt.Color(r, g, b));
                    if (r >= 221 && g >= 221 && b >= 221) {
                        timer.stop();
                    }
                });
                timer.start();
            }
        });
        getContentPane().add(AboutUs);
        AboutUs.setBounds(440, 10, 120, 44);

        Denuncia.setOpaque(false);
        Denuncia.setContentAreaFilled(false);
        Denuncia.setBorderPainted(false);
        Denuncia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Denuncia.setText("DENUNCIE");
        Denuncia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Denuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DenunciaActionPerformed(evt);
            }
        });
        Denuncia.setForeground(new java.awt.Color(221, 221, 221));

        Denuncia.addMouseListener(new java.awt.event.MouseAdapter() {
            private javax.swing.Timer timer;

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (timer !=null) {
                    timer.stop();
                }

                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.max(123, Denuncia.getForeground().getRed() - 10);
                    int g = Math.max(0, Denuncia.getForeground().getGreen() - 10);
                    int b = Math.max(0, Denuncia.getForeground().getBlue() - 10);
                    Denuncia.setForeground(new java.awt.Color(r, g, b));
                    if (r <= 123 && g <= 0 && b <= 0) {
                        timer.stop();
                    }
                });
                timer.start();
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (timer != null) {
                    timer.stop();
                }
                // Timer para a animação de volta à cor original
                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.min(255, Denuncia.getForeground().getRed() + 10);
                    int g = Math.min(255, Denuncia.getForeground().getGreen() + 10);
                    int b = Math.min(255, Denuncia.getForeground().getBlue() + 10);
                    Denuncia.setForeground(new java.awt.Color(r, g, b));
                    if (r >= 221 && g >= 221 && b >= 221) {
                        timer.stop();
                    }
                });
                timer.start();
            }
        });
        getContentPane().add(Denuncia);
        Denuncia.setBounds(154, 10, 120, 44);

        Home.setOpaque(false); // botão transparente
        Home.setContentAreaFilled(false); // Remove a cor de fundo
        Home.setBorderPainted(false); // Remove a borda
        Home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Home.setText("HOME");
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        Home.setForeground(new java.awt.Color(221, 221, 221));

        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            private javax.swing.Timer timer; //animação

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (timer !=null) {
                    timer.stop();
                }
                //mudança de cor
                timer = new javax.swing.Timer(18, e -> { //velocidade
                    int r = Math.max(123, Home.getForeground().getRed() - 10);
                    int g = Math.max(0, Home.getForeground().getGreen() - 10);
                    int b = Math.max(0, Home.getForeground().getBlue() - 10);
                    Home.setForeground(new java.awt.Color(r, g, b));
                    if (r <= 123 && g <= 0 && b <= 0) {
                        timer.stop(); // Para o timer quando a cor preta for atingida
                    }
                });
                timer.start(); // Começa a animação
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (timer != null) {
                    timer.stop();
                }
                // Timer para a animação de volta à cor original
                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.min(255, Home.getForeground().getRed() + 10);
                    int g = Math.min(255, Home.getForeground().getGreen() + 10);
                    int b = Math.min(255, Home.getForeground().getBlue() + 10);
                    Home.setForeground(new java.awt.Color(r, g, b));
                    if (r >= 221 && g >= 221 && b >= 221) {
                        timer.stop();
                    }
                });
                timer.start();
            }
        });
        getContentPane().add(Home);
        Home.setBounds(10, 10, 120, 44);

        Queimadas.setOpaque(false); // botão transparente
        Queimadas.setContentAreaFilled(false); // Remove a cor de fundo
        Queimadas.setBorderPainted(false); // Remove a borda
        Queimadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Queimadas.setText("QUEIMADAS");
        Queimadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Queimadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueimadasActionPerformed(evt);
            }
        });
        Queimadas.setForeground(new java.awt.Color(221, 221, 221));

        Queimadas.addMouseListener(new java.awt.event.MouseAdapter() {
            private javax.swing.Timer timer; //animação

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (timer !=null) {
                    timer.stop();
                }
                //mudança de cor
                timer = new javax.swing.Timer(18, e -> { //velocidade
                    int r = Math.max(0, Queimadas.getForeground().getRed() - 10);
                    int g = Math.max(0, Queimadas.getForeground().getGreen() - 10);
                    int b = Math.max(0, Queimadas.getForeground().getBlue() - 10);
                    Queimadas.setForeground(new java.awt.Color(r, g, b));
                    if (r <= 0 && g <= 0 && b <= 0) {
                        timer.stop(); // Para o timer quando a cor preta for atingida
                    }
                });
                timer.start(); // Começa a animação
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (timer != null) {
                    timer.stop();
                }
                // Timer para a animação de volta à cor original
                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.min(255, Queimadas.getForeground().getRed() + 10);
                    int g = Math.min(255, Queimadas.getForeground().getGreen() + 10);
                    int b = Math.min(255, Queimadas.getForeground().getBlue() + 10);
                    Queimadas.setForeground(new java.awt.Color(r, g, b));
                    if (r >= 221 && g >= 221 && b >= 221) {
                        timer.stop();
                    }
                });
                timer.start();
            }
        });
        getContentPane().add(Queimadas);
        Queimadas.setBounds(299, 10, 120, 44);

        Perfil1.setOpaque(false);
        Perfil1.setContentAreaFilled(false);
        Perfil1.setBorderPainted(false);
        Perfil1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Perfil1.setText("PERFIL");
        Perfil1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Perfil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Perfil1ActionPerformed(evt);
            }
        });
        Perfil1.setForeground(new java.awt.Color(221, 221, 221));

        Perfil1.addMouseListener(new java.awt.event.MouseAdapter() {
            private javax.swing.Timer timer;

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (timer !=null) {
                    timer.stop();
                }

                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.max(123, Perfil1.getForeground().getRed() - 10);
                    int g = Math.max(0, Perfil1.getForeground().getGreen() - 10);
                    int b = Math.max(0, Perfil1.getForeground().getBlue() - 10);
                    Perfil1.setForeground(new java.awt.Color(r, g, b));
                    if (r <= 123 && g <= 0 && b <= 0) {
                        timer.stop();
                    }
                });
                timer.start();
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (timer != null) {
                    timer.stop();
                }
                // Timer para a animação de volta à cor original
                timer = new javax.swing.Timer(18, e -> {
                    int r = Math.min(255, Perfil1.getForeground().getRed() + 10);
                    int g = Math.min(255, Perfil1.getForeground().getGreen() + 10);
                    int b = Math.min(255, Perfil1.getForeground().getBlue() + 10);
                    Perfil1.setForeground(new java.awt.Color(r, g, b));
                    if (r >= 221 && g >= 221 && b >= 221) {
                        timer.stop();
                    }
                });
                timer.start();
            }
        });
        getContentPane().add(Perfil1);
        Perfil1.setBounds(580, 10, 120, 44);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Documentos\\NetBeansProjects\\A3_Testes\\src\\main\\resources\\images\\TelaQueimadas.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 960, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void abrirGoogleMaps(String endereco) {
    try {
        String enderecoCodificado = URLEncoder.encode(endereco, "UTF-8");
        String url = "https://www.google.com/maps/search/?api=1&query=" + enderecoCodificado;

        if (Desktop.isDesktopSupported()) {
            Desktop.getDesktop().browse(new URI(url));
            System.out.println("Abrindo o google maps!");
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possível abrir o navegador!");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao abrir o Google Maps: " + e.getMessage());
    }
}

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed
        // TODO add your handling code here:
        
        String cidade = txtcidade.getText();
        String sql = "";
        
        DefaultTableModel model = new DefaultTableModel
        (new String[]{"Estado", "Cidade", "Rua", "Número", "Data", "Hora", "Gravidade"},0) {
                
            public boolean isCellEditable(int row, int column) {
            return false;
            }
        };
        
        if ("".equals(cidade))
            sql = "SELECT * FROM tb_denuncias ORDER BY numden DESC";
        else
            sql = "SELECT * FROM tb_denuncias WHERE cidadeden LIKE ? OR estadoden LIKE ? OR endeden LIKE ? OR dataden LIKE ? OR gravden LIKE ? ORDER BY numden DESC";
        
        ConnectionFactory cf = new ConnectionFactory();
        
        try(Connection conn = cf.obtemConexao();
                PreparedStatement ps = conn.prepareStatement(sql);) {
            if (!"".equals(cidade)) {
                
                String procurar = "%" + cidade + "%";
                
                ps.setString(1, procurar);
                ps.setString(2, procurar);
                ps.setString(3, procurar);
                ps.setString(4, procurar);
                ps.setString(5, procurar);
                
            }
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
                String txtestado = rs.getString("estadoden");
                String txtcidade = rs.getString("cidadeden");
                String txtrua = rs.getString("endeden");
                String txtnum = rs.getString("numeden");
                String txtdata = rs.getString("dataden");
                String txthora = rs.getString("horaden");
                String txtgrav = rs.getString("gravden");
                
                model.addRow(new Object[]{txtestado, txtcidade, txtrua, txtnum, txtdata, txthora, txtgrav});
                        
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Não localizado!");
        }    
        
        tabela.setModel(model);
    }//GEN-LAST:event_listarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
         // TODO add your handling code here:
        int linhaSelec = tabela.getSelectedRow();
        
        if (linhaSelec == -1) {
           JOptionPane.showMessageDialog(null, "Por favor, selecione uma coluna!");
           return;
        }
        
        String rua = (String) tabela.getValueAt(linhaSelec, 2);
        String num = (String) tabela.getValueAt(linhaSelec, 3);
        String cidade = (String) tabela.getValueAt(linhaSelec, 1);
        String estado = (String) tabela.getValueAt(linhaSelec, 0);
        
        String endereco = rua + ", " + num + ", " + cidade + ", " + estado;
        
        abrirGoogleMaps(endereco);
    }//GEN-LAST:event_buscarActionPerformed

    private void PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilActionPerformed
        // TODO add your handling code here:
        int x = this.getLocation().x;
        int y = this.getLocation().y;

        Perfil perfil = new Perfil();
        perfil.setLocation(x, y);
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PerfilActionPerformed

    private void Perfil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Perfil1ActionPerformed
        // TODO add your handling code here:
        int x = this.getLocation().x;
        int y = this.getLocation().y;

        Perfil perfil = new Perfil();
        perfil.setLocation(x, y);
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Perfil1ActionPerformed

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed
        // TODO add your handling code here:
        int x = this.getLocation().x;
        int y = this.getLocation().y;

        SobreNos sobreNos = new SobreNos();
        sobreNos.setLocation(x,y);
        sobreNos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AboutUsActionPerformed

    private void DenunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DenunciaActionPerformed
        // TODO add your handling code here:
        //pega a posição atual da tela
        int x = this.getLocationOnScreen().x;
        int y = this.getLocationOnScreen().y;

        Denuncia denuncia = new Denuncia();
        denuncia.setLocation(x, y);
        denuncia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DenunciaActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        int x = this.getLocation().x;
        int y = this.getLocation().y;

        Home home = new Home();
        home.setLocation(x,y);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void QueimadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueimadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QueimadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Queimadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Queimadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Queimadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Queimadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Queimadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUs;
    private javax.swing.JButton Denuncia;
    private javax.swing.JButton Home;
    private javax.swing.JButton Perfil;
    private javax.swing.JButton Perfil1;
    private javax.swing.JButton Queimadas;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listar;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtcidade;
    // End of variables declaration//GEN-END:variables
}
